### ISSUE TITLE
Add NBT storage access to plugins

### ISSUE THREAD

**Issue by slimshadeey1** [PoweredRails/RailsAPI#1]
### TODO
- [ ] Plugin Interface (Via Rails)
- [ ] Auto Save
- [ ] Shutdown handling
- [ ] Corruption Handling
- [ ] NBT Write Event
- [ ] Minecraft NBT Data Manipulation safety
- [ ] Protection of other plugins stored data
- [ ] Objects to be r/w from

________________________
## Abstract Idea
- Add interface to store data on player file to prevent oversized db that can crash a server.
- Provides better organization of data

**Comment by RONNOC777** [comment]
*  TODO: Add Load player, which should return a NBT object for the specified plugin.
 *  TODO: NBT Object will be an Object that is defined with an annotation interface.
 *  TODO: NBT Object is Plugin specific, so cannot modify others
 *  TODO: NBT Object saving will add saving to a dispatch, for rw lock exceptions.
 *  TODO: NBT Object will be annotation interface
 *  TODO: NBT accessor will be abstract class implementing this interface.
 *  TODO: This interface is for in house management of data handling including saving on shutdown and loading on logon.
 *  TODO: Can be run by events (Player disconnect)
 *  TODO: Needs Player Object for any player methods!
